PEST_TAXONOMY_TERMS = {
    "cucaracha": "cucarachas",
    "cucarachas": "cucarachas",
    "cockroach": "cucarachas",
    "cockroaches": "cucarachas",
    "hormiga": "hormigas",
    "hormigas": "hormigas",
    "ant": "hormigas",
    "ants": "hormigas",
    "roedor": "roedores",
    "roedores": "roedores",
    "rodent": "roedores",
    "rodents": "roedores",
    "rata": "roedores",
    "ratas": "roedores",
    "ratón": "roedores",
    "ratones": "roedores",
    "raton": "roedores",
    "unknown": "unknown",
}
